# Site settings
title: Branan's Portfolio
description: Branan Harrison's professional portfolio site
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Branan Harrison
user_title: ""
user_job_title: OMSCS Student at Georgia Tech
email: brananrharrison [at] gmail.com
twitter_username: ""
github_username:  brananharrison

exclude: ['package.json', 'src' , 'node_modules']

# Automatic SCSS processings
sass:
  style: compressed
  sass_dir: src/styles
  css_dir: assets/css
